export const GET_WORK_REQUEST = "GET_WORK_REQUEST";
export const GET_WORK_SUCCESS = "GET_WORK_SUCCESS";
export const GET_WORK_FAILURE = "GET_WORK_FAILURE";

export const PUT_WORK_REQUEST = "PUT_WORK_REQUEST";
export const PUT_WORK_SUCCESS = "PUT_WORK_SUCCESS";
export const PUT_WORK_FAILURE = "PUT_WORK_FAILURE";

export const POST_WORK_REQUEST = "POST_WORK_REQUEST";
export const POST_WORK_SUCCESS = "POST_WORK_SUCCESS";
export const POST_WORK_FAILURE = "POST_WORK_FAILURE";

export const DELETE_WORK_REQUEST = "DELETE_WORK_REQUEST";
export const DELETE_WORK_SUCCESS = "DELETE_WORK_SUCCESS";
export const DELETE_WORK_FAILURE = "DELETE_WORK_FAILURE";

export const REDACTION_WORK = "REDACTION_WORK";
export const GET_API_ACTIVE = "GET_API_ACTIVE";
export const GET_API_DEACTIVATE = "GET_API_DEACTIVATE";
